#!/bin/sh

usage() {
	echo "usage: $(basename $0) [-h] [on|off]"
}

if test $# -gt 1 || test "$1" = "-h"; then
	usage
	exit
elif test $# -eq 0; then
	STATE=$(xssstate -s)
elif test "$1" = "on"; then
	STATE="disabled"
elif test "$1" = "off"; then
	STATE="on"
else
	usage
	exit
fi

case "$STATE" in
	disabled)
	   xset s on
	   xset +dpms
	   ;;
	*)
	   xset s off
	   xset -dpms
	   ;;
esac
exit
